### ISSUE TITLE
Fail to get job status in PBSPro

### ISSUE THREAD

**Issue by GiulioCentorame** [Snakemake-Profiles/generic#8]
**Describe the bug**
When using PBSPro, the profile config fails to get the job status from `qstat`. Sample of a `qstat` output below:
```
$ qstat -f -x 711291.name
    Job Id: 711291.name
    Job_Name = Something
    Job_Owner = user@node077
    resources_used.cpupercent = 1601
    resources_used.cput = 15:00:35
    resources_used.mem = 24722464kb
    resources_used.ncpus = 10
    resources_used.vmem = 35426256kb
    resources_used.walltime = 00:56:20
    job_state = R
    queue = normal
    server = delta2
    Account_Name = uqdmizik
    Checkpoint = u
    ctime = Fri Nov  4 12:12:33 2022
    Error_Path = xxxx:/some/path.e711291
    exec_host = xxxx/0*10
    exec_vnode = (xxxx:ncpus=10:mem=104857600kb)
    Hold_Types = n
    Join_Path = n
    Keep_Files = n
    Mail_Points = a
    mtime = Fri Nov  4 13:08:52 2022
    Output_Path = xxxx:/some/path.o711291
    Priority = 0
    qtime = Fri Nov  4 12:12:33 2022
```
I am using the vanilla profile with an added `.name` to the jobs, as our cluster uses `jobid.name` for the job IDs

***Cluster system***
PBSPro
- [x] I selected the correct cluster system in the `cluster_spec.yaml`

**Error message**
```
CLUSTER: 2022-11-04 13:07:26 Automatically choose best queue to submit
CLUSTER: 2022-11-04 13:07:27 Choose queue: normal
CLUSTER: 2022-11-04 13:07:27 submit command: qsub -N strip_comments -l nodes=1:ppn=1 -l mem=1000mb -q normal /home/uqgcento/repositories/mrxp_breastfed_cog/.snakemake/tmp.v1zkv45t/snakejob.strip_comments.2.sh
Submitted job 2 with external jobid '711296'.
Traceback (most recent call last):
  File "/home/uqgcento/.config/snakemake/generic/pbs_status.py", line 18, in <module>
    xmldoc = ET.ElementTree(ET.fromstring(res.stdout.decode())).getroot()
  File "/home/uqgcento/mambaforge/envs/snakemake/lib/python3.10/xml/etree/ElementTree.py", line 1342, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
WorkflowError:
Failed to obtain job status. See above for error message.
```

**Comment by SilasK** [comment]
I cannot test the profile on a PBS cluster system, unfortunately. 
My profile has the function to select automatically the queue, but maybe there is another PBS profile that you could use. https://github.com/Snakemake-Profiles

For your error, it seems that the pbs_status expects a XML string, but you got plain text. 

Is there a way to get the ouput of your qstat in xml format?

**Comment by SilasK** [comment]
Otherwise is there a way to configure your qstat to return only the job_state `job_state`?

**Comment by GiulioCentorame** [comment]
Thank you, this makes a lot of sense. I attempted to adapt the status script using `qstat -f json`, which is now an option. As mentioned in the PR, though, I cannot test it on a queue with the default PBSPro, and it currently fails to detect completed jobs on my cluster (as they are immedately removed from the `qstat` output).
